### PR TITLE
Code/items powerups

### PR DESCRIPTION
**Pull request by speterius**
I added power up behavior:

1) An abstract class for picking up things: triggers an effect when a player walks through.
2) A speed up behavior which has an effect duration and a re-spawn duration.

### CODE REVIEW

**Review by guenterg — COMMENTED** [review]
You have upgrade your unity version slightly. The rest of the team is still on 2019.4.8f1.

**Comment by speterius** [comment]
> You have upgrade your unity version slightly. The rest of the team is still on 2019.4.8f1. 

@guenterg Reverted the upgrade. Should be the same now.

**Review by Alex-Sindledecker — APPROVED** [review]
The code looks good but in "SpeedPowerUpObject.cs" in the update method you use bitwise operators instead of logical operators. It isn't really a problem but by using logical operators, you can possibly eliminate the second check in the expression.

**Review by guenterg — APPROVED** [review]
Looks good. Bring it forward and we can make sure it plays nice with the rest of the code.

**Pull request merged**
